[package]
name = "unfocol"
version = "2.0.2"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
atomicwrites = "0.4.4"
csscolorparser = "0.8.3"
directories = "6.0.0"
egui_extras = "0.34.2"
egui-modal = "0.6.0"
env_logger = "0.11.10"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
thiserror = "2.0.18"
displaydoc = "0.2.6"
notify = "8.2.0"

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.34.2", default-features = false, features = ["glow", "default_fonts", "persistence", "accesskit", "wayland"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
eframe = { version = "0.34.2", default-features = false, features = ["wgpu", "default_fonts", "persistence", "accesskit"] }
